const mongoose = require('mongoose');

/**
 * Payment Schema
 * 
 * ACADEMIC PURPOSE:
 * This schema implements a SIMULATED UPI payment workflow for demonstration.
 * It does NOT integrate with real banking systems or payment gateways.
 * 
 * KEY FEATURES:
 * 1. Mock transaction reference generation
 * 2. Status tracking (INITIATED → SUCCESS/FAILED)
 * 3. Fraud detection via validation rules
 * 4. Order-payment coupling
 * 
 * SECURITY NOTES:
 * - No real banking credentials are stored
 * - No actual money transfers occur
 * - Transaction references are mock UUIDs
 * 
 * FRAUD PREVENTION RULES (non-AI):
 * - One payment per order (enforced by unique index)
 * - Amount must match order total exactly
 * - Duplicate confirmations are rejected
 */

const PaymentSchema = new mongoose.Schema({
  // Reference to the order being paid for
  orderId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Order',
    required: [true, 'Order ID is required'],
    unique: true  // FRAUD RULE: Only one payment per order
  },
  
  // Consumer making the payment
  payerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Payer ID is required']
  },
  
  // Payment amount (must match order total)
  amount: {
    type: Number,
    required: [true, 'Amount is required'],
    min: [0, 'Amount cannot be negative']
  },
  
  // Payment method (currently only UPI supported)
  method: {
    type: String,
    enum: {
      values: ['UPI', 'COD'],
      message: 'Payment method must be UPI or COD'
    },
    default: 'UPI'
  },
  
  // Payment status lifecycle
  // INITIATED → SUCCESS or FAILED
  status: {
    type: String,
    enum: {
      values: ['INITIATED', 'SUCCESS', 'FAILED'],
      message: 'Invalid payment status'
    },
    default: 'INITIATED'
  },
  
  // Mock UPI transaction reference
  // Format: MOCK-UPI-{timestamp}-{random}
  transactionRef: {
    type: String,
    unique: true,
    sparse: true  // Allow null for COD payments
  },
  
  // UPI ID used for payment (mock, not validated)
  upiId: {
    type: String,
    trim: true
  },
  
  // Failure reason (if status = FAILED)
  failureReason: {
    type: String
  },
  
  // Fraud detection flags
  fraudFlags: [{
    type: String,
    reason: String,
    detectedAt: Date
  }],
  
  // Whether payment was confirmed
  confirmedAt: {
    type: Date
  },
  
  // For audit trail
  initiatedByRole: {
    type: String,
    enum: ['CONSUMER', 'SYSTEM'],
    default: 'CONSUMER'
  }
}, { 
  timestamps: true 
});

// Index for fast order lookups
PaymentSchema.index({ orderId: 1 });

// Index for payer lookups
PaymentSchema.index({ payerId: 1 });

// Index for status-based queries
PaymentSchema.index({ status: 1, createdAt: -1 });

/**
 * Generate a mock UPI transaction reference
 * Format: MOCK-UPI-{timestamp}-{random6chars}
 * 
 * ACADEMIC NOTE: This is NOT a real UPI reference.
 * Real UPI references are generated by NPCI/banks.
 */
PaymentSchema.statics.generateTransactionRef = function() {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8).toUpperCase();
  return `MOCK-UPI-${timestamp}-${random}`;
};

/**
 * Check if payment can be confirmed
 * Returns { canConfirm: boolean, reason?: string }
 */
PaymentSchema.methods.canBeConfirmed = function() {
  if (this.status === 'SUCCESS') {
    return { canConfirm: false, reason: 'Payment already confirmed' };
  }
  
  if (this.status === 'FAILED') {
    return { canConfirm: false, reason: 'Payment has already failed' };
  }
  
  if (this.status !== 'INITIATED') {
    return { canConfirm: false, reason: 'Invalid payment state' };
  }
  
  return { canConfirm: true };
};

/**
 * Add a fraud flag to this payment
 */
PaymentSchema.methods.addFraudFlag = function(type, reason) {
  this.fraudFlags.push({
    type,
    reason,
    detectedAt: new Date()
  });
};

module.exports = mongoose.model('Payment', PaymentSchema);
